services:
  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    # restart: always
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: dragonfly --dbnum=1
